### ISSUE TITLE
WeCatch not working since yesterday 07/10/2023. 

### ISSUE THREAD

**Issue by cpajamasam** [daydreamer1222/WeCatch-Android#116]
WeCatch not working since yesterday 07/10/2023, tried on different Samsung devices where it was working perfectly. Thank you!

**Comment by jyr2711** [comment]
Same Here.

Different devices and not working on any of them. Seems like wecatch is unable to get info from the game

**Comment by Ziming-Wang** [comment]
Can confirm the issue with IOS devices as well. Error page says data not in the correct format.

**Comment by IanXTsai** [comment]
HTC U11 Android 8，ASUS ZF3 Android 7 , wecatch can't work from yesterday.

**Comment by ceduardogomes** [comment]
Poço x3 pro, vayu. Don't work from yesterday.

**Comment by cpajamasam** [comment]
![Screenshot_20230712_095147_WeCatch](https://github.com/daydreamer1222/WeCatch-Android/assets/69858090/25a6c251-2cf5-4a48-9439-6d1ed95125f0)
![Screenshot_20230712_095147_WeCatch](https://github.com/daydreamer1222/WeCatch-Android/assets/69858090/029fbb78-7286-4f39-911a-084bc9ed35c4)
![Screenshot_20230712_095031_WeCatch](https://github.com/daydreamer1222/WeCatch-Android/assets/69858090/bc958890-877d-4ee2-89ee-7313d35a904a)

**Comment by cpajamasam** [comment]
![Screenshot_20230712_095147_WeCatch](https://github.com/daydreamer1222/WeCatch-Android/assets/69858090/f364a7aa-e217-4447-bc34-58d3791a349b)
![Screenshot_20230712_095211_WeCatch](https://github.com/daydreamer1222/WeCatch-Android/assets/69858090/a0d5e918-0862-4517-81fc-747d208b2100)
![Screenshot_20230712_095031_WeCatch](https://github.com/daydreamer1222/WeCatch-Android/assets/69858090/b81845c3-f859-462b-b5b2-ae6e066ba485)

**Comment by cpajamasam** [comment]
Thanks a lot! Fixed already.

**Comment by cpajamasam** [comment]
Thanks a lot! Fixed already. This has been and is the best app to track pokemons. Thanks again for your hard work.

**Comment by cpajamasam** [comment]
Well, it is still with some issues, I think it needs more tuning. Not showing many pokemons when you search by IV (0% by example) and this window is not loading properly, as it was before it stopped working. Just to mention some. Thanks in advance! And keep your great work up!

**Comment by jyr2711** [comment]
Thanks for fixing It. Working fine.

**Comment by cpajamasam** [comment]
Perfect, thank you!

**Comment by dtu03830** [comment]
wecatch is not working on January 14, 2024

**Comment by MazANTO** [comment]
Same with me. WeCatch is not working from January 14, 2024. Please advise how to solve it. Thank you.

**Comment by MazANTO** [comment]
I already tried to find the solution through the internet, but could not find.
